apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "deploy.fullname" . }}
  labels:
  {{- include "deploy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{ .Chart.Name }}-{{ .Release.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- end }}
    timestamp: "{{ now | date "20060102150405" }}"
spec:
  refreshInterval: {{ .Values.refInterval }}
  secretStoreRef:
    name: {{ .Values.vaultBackendName }} #vault-backend
    kind: SecretStore
  target:
    name: {{ include "deploy.fullname" . }}
    creationPolicy: Owner
  dataFrom: 
  - extract:
      key: {{ .Values.vaultPath }} 
