apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.vaultBackendName }}
spec:
  provider:
    vault:
      server: {{ .Values.vaultURL }}
      path: {{ .Values.vaultKVName }}
      version: {{ .Values.vaultKVVersion }}
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: {{ .Values.vaultToken }}
